version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data/pgdata

volumes:
  data: {}
