version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    networks:
      - webnet
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - webnet
networks:
  webnet:
